package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Status;
import model.Status.IStatus;
import model.ToDoItem;

import java.time.LocalDate;
import java.util.ArrayList;

import javafx.event.ActionEvent;

public class MainSceneController {
	private ToDoItem toDoItem = null;
	private ArrayList<ToDoItem> toDoList = new ArrayList<ToDoItem>();
	@FXML
	private TextField txtNewItem;
	@FXML
	private Button btnAddNew;
	@FXML
	private TableView<ToDoItem> tblToDoList;
	@FXML
	private TableColumn<ToDoItem, Integer> colID;
	@FXML
	private TableColumn<ToDoItem, Integer> colDescription;
	@FXML
	private TableColumn<ToDoItem, Status.IStatus> colStatus;
	@FXML
	private TableColumn<ToDoItem, LocalDate> colCreated;
	@FXML
	private TableColumn<ToDoItem, LocalDate> colCompleted;
	@FXML
	private TableColumn<ToDoItem, Integer> colAge;

	@FXML
	private Button btnComplete;
	@FXML
	private Button btnBlocked;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnWriteToFile;
	@FXML
	private Button btnLoadFromFile;

	// Event Listener on Button[#btnAddNew].onAction
	@FXML
	public void btnAddNewClicked(ActionEvent event) {
		//Stage mainWindow = (Stage) txtNewItem.getScene().getWindow();
		String newActivity = txtNewItem.getText();
		toDoItem = new ToDoItem(newActivity);
		toDoList.add(toDoItem);
	}
	// Event Listener on Button[#btnComplete].onAction
	@FXML
	public void btnCompleteClicked(ActionEvent event) {
		toDoItem.setStatus(IStatus.COMPLETE);
	}
	// Event Listener on Button[#btnBlocked].onAction
	@FXML
	public void btnBlockedClicked(ActionEvent event) {
		toDoItem.setStatus(IStatus.BLOCKED);
		Stage mainWindow = (Stage) txtNewItem.getScene().getWindow();
		mainWindow.setTitle(toDoItem.getStatus().name());
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void btnDeleteClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnWriteToFile].onAction
	@FXML
	public void btnWriteToFileClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLoadFromFile].onAction
	@FXML
	public void btnLoadFromFileClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
